name: CI

on:
  push:
    branches: [main,backend-auth]
  pull_request:
    branches: [main,backend-auth]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install --prefix backend
      - run: npm test --prefix backend
      - run: npm run test:coverage --prefix backend

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: backend/coverage/lcov.info
