name: CI

on:
  push:
    branches: [ backend-api ]
  pull_request:
    branches: [ backend-api ]   
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Set environment variables
        run: echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV

      - run: npm install

      - name: Skip tests temporarily
        run: echo "⚠️ Skipping tests and coverage temporarily..."

      # - run: npm test -- --coverage
      #   continue-on-error: true    # ← tests failures won’t stop the job

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage/lcov.info
      #   continue-on-error: true    # ← Codecov errors won’t stop the job

      # - name: Install serve, ngrok, and jq (required for URL extraction)
      #   run: |
      #     npm install -g serve ngrok
      #     sudo apt-get install -y jq

      # - name: Serve and expose coverage report via ngrok
      #   run: |
      #     npx serve -s ./coverage/lcov-report -l 4000 &
      #     npx ngrok http 4000 > /dev/null &
      #     sleep 5
      #     NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
      #     echo "Coverage report is live at: $NGROK_URL"
      #     echo "REPORT_URL=$NGROK_URL" >> $GITHUB_ENV
