name: CI

on:
  push:
    branches: ["backend-api"]
  pull_request:
    branches: ["backend-api"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Set environment variables
        run: echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV

      - run: npm install
      - run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info

      - name: Install serve, ngrok, and jq (required for URL extraction)
        run: |
          npm install -g serve ngrok
          sudo apt-get install -y jq  # Required to parse ngrok's JSON output

      - name: Serve and expose coverage report via ngrok
        run: |
          # Start the server in the background
          npx serve -s ./coverage/lcov-report -l 4000 &
          
          # Start ngrok and capture its public URL
          npx ngrok http 4000 > /dev/null &
          sleep 5  # Wait for ngrok to initialize
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          
          # Make the URL available in workflow logs
          echo "Coverage report is live at: $NGROK_URL"
          echo "REPORT_URL=$NGROK_URL" >> $GITHUB_ENV
